### ISSUE TITLE
Update Documentation to reflect VSCode

### ISSUE THREAD

**Issue by story645** [GCDigitalFellows/installdri.github.io#5]
Use VSCode instead of sublime since it has clean git integration: https://code.visualstudio.com/

attn: @majorgreys

**Comment by majorgreys** [comment]
I do not have any experience with Sublime but VSCode has made a huge splash over the past year. Microsoft's team has been on a monthly release schedule which has meant new features get added regularly and old bugs don't stick around long. It is open source (https://github.com/Microsoft/vscode), based on web technologies (HTML, CSS, JS), and has an impressive array of plugins. If folks want, I can do a demo and explain how I configure mine.

I had used Atom before, which was based on similar technology (Electron). But VSCode was better in performance right out of the gate. Also I'd much rather use TypeScript (which is what VSCode is written in) rather than CoffeeScript (used by Atom). TypeScript has become one of the best transpiling javascript compilers.
